# Generated by Django 2.0.1 on 2018-07-20 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='partner',
            name='links',
        ),
        migrations.AddField(
            model_name='link',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='service.Partner'),
        ),
    ]
