# Generated by Django 2.0.1 on 2018-01-26 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20180126_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='service.Partner'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(),
        ),
    ]
