# Generated by Django 2.0.1 on 2018-01-29 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20180126_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('location', models.CharField(max_length=256, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('attendees', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='link',
            name='partner',
        ),
        migrations.AddField(
            model_name='partner',
            name='links',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.AddField(
            model_name='engagement',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='service.Partner'),
        ),
        migrations.AddField(
            model_name='contact',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='service.Partner'),
        ),
        migrations.AddField(
            model_name='category',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='service.Partner'),
        ),
    ]
