# Generated by Django 2.0.1 on 2018-08-14 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20180802_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='timestamp',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
