# Generated by Django 2.0.1 on 2018-08-14 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_completed',
            new_name='completed',
        ),
    ]
