# Generated by Django 2.0.1 on 2018-02-19 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20180219_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='service.Partner'),
        ),
    ]
