# Generated by Django 2.0.1 on 2018-06-21 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
