# Generated by Django 2.0.1 on 2018-06-21 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20180621_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='partner',
            new_name='partner_id',
        ),
    ]
