# Generated by Django 2.0.1 on 2018-06-21 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_auto_20180621_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='partner_id',
            new_name='partner',
        ),
    ]
