# Generated by Django 2.0.1 on 2018-06-21 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_auto_20180621_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='partner',
        ),
    ]
