# Generated by Django 2.0.1 on 2018-06-21 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_remove_comment_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='partner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='service.Partner'),
            preserve_default=False,
        ),
    ]
