# Generated by Django 2.0.1 on 2018-06-25 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_comment_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner_Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='partner',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner_categories',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Category'),
        ),
        migrations.AddField(
            model_name='partner_categories',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_categories', to='service.Partner'),
        ),
    ]
