# Generated by Django 2.0.1 on 2018-06-29 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_auto_20180625_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Category')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='service.Partner')),
            ],
        ),
        migrations.RemoveField(
            model_name='partner_categories',
            name='category',
        ),
        migrations.RemoveField(
            model_name='partner_categories',
            name='partner',
        ),
        migrations.DeleteModel(
            name='Partner_Categories',
        ),
    ]
