# Generated by Django 2.0.1 on 2018-07-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_auto_20180629_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='logo',
            field=models.TextField(null=True),
        ),
    ]
